name: Release

on:
  push:
    branches:
      - 'main'
      - 'make-a-build' # removeme

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Setup Java 11"
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: latest
    - name: Build jar
      run: clj -T:build jar
# TODO
#    - name: Deploy to Clojars
#      run: lein deploy clojars
#      env:
#        CLOJARS_USER: opqdonut
#        CLOJARS_DEPLOY_TOKEN: "${{ secrets.CLOJARS_DEPLOY_TOKEN }}"
