name: Release

on:
  push:
    branches:
      - 'main'
      - 'make-a-build' # removeme

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Setup Java 11"
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: latest
    - name: Build jar
      run: clojure -T:build jar
    - name: Deploy to Clojars
      run: clj -X:deploy
      env:
        CLOJARS_USERNAME: ilmoraunio
        CLOJARS_PASSWORD: "${{ secrets.CLOJARS_DEPLOY_TOKEN }}"
